/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jadwal.sholat;

import conn.koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class time extends javax.swing.JFrame {
    Connection conn = (Connection) koneksi.koneksiDB();
    time home;
    String id; 
    ArrayList<String> arrayls = new ArrayList<String>();
    
    public void getData() {
        DefaultTableModel tabModel;
        Object[] row = {"No", "Sholat", "Waktu"};
        tabModel = new DefaultTableModel(null, row);
        tb_hasil.setModel(tabModel);
        try {
            arrayls.clear();
            Statement st = conn.createStatement();
            String query = "SELECT * FROM jadwal ORDER BY id ASC";
            ResultSet set = st.executeQuery(query);

            int a = 1;
            while (set.next()) {
                String nomor, sholat, waktu, id;
                nomor = String.valueOf(a + tabModel.getRowCount());
                id = set.getString("id");
                sholat = set.getString("sholat");
                waktu = set.getString("waktu");

                String[] data = {nomor, sholat, waktu, id};
                tabModel.addRow(data);
                arrayls.add(id);
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
    public time() {
        initComponents();
        getData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jadwal = new javax.swing.JComboBox<>();
        tampilkan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_hasil = new javax.swing.JTable();
        btn_simpan = new javax.swing.JButton();
        refresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jadwal.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jadwal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Subuh", "Dzuhur", "Ashar", "Magrib", "Isya" }));
        jadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jadwalActionPerformed(evt);
            }
        });

        tampilkan.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        tampilkan.setText("Tampilkan");
        tampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilkanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Jadwal Sholat");

        tb_hasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(tb_hasil);

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn_simpan)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(refresh))
                                .addComponent(tampilkan))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(tampilkan)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan)
                    .addComponent(refresh))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilkanActionPerformed
        // TODO add your handling code here:
        if (jadwal.getSelectedItem().toString().equalsIgnoreCase("Subuh")){
   String Subuh;
    Subuh = " 04.38 ";
    tampilkan.setText (Subuh);
        }
        if (jadwal.getSelectedItem().toString().equalsIgnoreCase("Dzuhur")){
   String Dzuhur;
    Dzuhur = " 12.04 ";
    tampilkan.setText (Dzuhur);
    }
      if (jadwal.getSelectedItem().toString().equalsIgnoreCase("Ashar")){
   String Ashar;
    Ashar = " 15.28 ";
    tampilkan.setText (Ashar);
    }
      if (jadwal.getSelectedItem().toString().equalsIgnoreCase("Magrib")){
   String Magrib;
    Magrib = " 18.10 ";
    tampilkan.setText (Magrib);
    }
      if (jadwal.getSelectedItem().toString().equalsIgnoreCase("Isya")){
   String Isya;
    Isya = " 19.21 ";
    tampilkan.setText (Isya);
}

    }//GEN-LAST:event_tampilkanActionPerformed

    private void jadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jadwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jadwalActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        String
                tampil, simpan;
        
        //getdata
        tampil = tampilkan.getText();
        simpan = jadwal.getSelectedItem().toString();
        
        if (tampil.isEmpty() || simpan.isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Di isi!");
        } else {
            try {
                Statement st = conn.createStatement();
                String query = "INSERT INTO `jadwal`(`sholat`, `waktu`) "
                        + "VALUES ('" + simpan + "', '" + tampil + "')";
                int set = st.executeUpdate(query);
                home.getData();
                dispose();
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        getData();
    }//GEN-LAST:event_refreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new time().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jadwal;
    private javax.swing.JButton refresh;
    private javax.swing.JButton tampilkan;
    private javax.swing.JTable tb_hasil;
    // End of variables declaration//GEN-END:variables

}
